name: 恢复serv00_ct8_crontab 任务列表

on:
  schedule:
    - cron: '*/5 * * * *'  # 每10分钟执行一次
  workflow_dispatch:
jobs:
  
  restore_and_notify:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout codes'
        uses: actions/checkout@v1
        
      - name: '访问网页'
        run: curl $(echo "aHR0cHM6Ly9zcXNoaW5pbmcuY3Q4LnBsL2Nyb25yZWNvdmVyeS5waHA/dG9rZW49ZXlKdVlXMWxJam9pWVdSdGFXNGlMQ0p3YzNjaU9pSndZWE56ZDI5eVpDSjkK"|base64 -d)

      
