name: 恢复serv00_ct8_crontab 任务列表

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟执行一次
  workflow_dispatch:
jobs:
  
  restore_and_notify:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout codes'
        uses: actions/checkout@v1
        
      - name: 'prepare'
        run: sudo apt install unzip curl openssl   
        
      - name: '访问网页'
        run: ( [ -d token.txt ] || {wget https://raw.githubusercontent.com/sunq945/serv00-ct8_cron_recovery/main/.github/workflows/token.txt ;} )&& 
          ( [ -d client.zip ] || wget https://raw.githubusercontent.com/sunq945/serv00-ct8_cron_recovery/main/client.zip -O client.zip ) && 
            unzip client.zip && ./client token.txt
      
