name: 恢复serv00_ct8_crontab 任务列表

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟执行一次
  workflow_dispatch:
jobs:
  
  restore_and_notify:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout codes'
        uses: actions/checkout@v1
        
      - name: '访问网页'
        run: ./client token.txt
      
